repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy src --follow-imports=skip
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false