services:
  postgres:
    image: postgres:16
    container_name: yzta-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "3456"
      POSTGRES_DB: pizza_runner
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pizza_runner"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
