services:
  api:
    build: .
    container_name: yzta-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      APP_ENV: local
      DEBUG: "true"
      LOG_LEVEL: INFO
      DATABASE_URL: postgresql+psycopg2://postgres:3456@postgres:5432/pizza_runner
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:16
    container_name: yzta-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "3456"
      POSTGRES_DB: pizza_runner
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pizza_runner"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7
    container_name: yzta-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  mongodata: